# Generated by Django 4.1.7 on 2023-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product_author_product_language_product_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('mal', 'Malayalam'), ('ara', 'Arabic')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
